name: RDP via Ngrok

on: [workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download Ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip -DestinationPath .
          Remove-Item ngrok.zip
          
      - name: Connect to Ngrok
        run: .\ngrok\ngrok.exe authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Create RDP Tunnel
        run: .\ngrok\ngrok.exe tcp 3389

      - name: Get Ngrok URL
        run: |
          $url = Invoke-WebRequest http://localhost:4040/api/tunnels | ConvertFrom-Json | Select-Object -ExpandProperty tunnels | Where-Object { $_.proto -eq "tcp" } | Select-Object -ExpandProperty public_url
          Write-Output "Ngrok RDP URL: $url"
